name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        php-versions: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          ini-values:  zend.assertions=1,  assert.exception=1

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-publish
        working-directory: ./tools/apigen

      - name: Cache Composer packages
        id: composer-apigen-cache
        uses: actions/cache@v3
        with:
          path: tools/apigen/vendor
          key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('tools/apigen/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-versions }}-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        working-directory: ./tools/apigen

      - name: Configure autoloader
        run: composer dumpautoload --no-dev

      - name: Generate documentation
        run: ./tools/apigen/apigen

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs'

  deploy:
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    concurrency:
      group: "pages"
      cancel-in-progress: true

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"; env

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
